parameters:
#    gf_project_info.example.class: utement\GFProjectInfoBundle\Example

services:
#    gf_project_info.example:
#        class: %gf_project_info.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
